# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required
r:
  - oldrel
  - release
  - devel
  - bioc-devel
  - bioc-release

install: true

script:
  - cd unit-testing && bash install.sh && bash run_tests.sh

