# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required
r:
  - oldrel
  - release
  - devel
  - bioc-devel
  - bioc-release

install:
  - R -e 'devtools::install_deps(dep = T)'

script:
  - cd unit-testing && bash run_tests.sh

